### ISSUE TITLE
Problema com cálculo

### ISSUE THREAD

**Issue by davioliveiraweb** [phscezario/woocommence-rte-rodonaves-shipping#1]
Estou enfrentando um problema com o cálculo do valor. Estou trabalhando em uma loja onde a medida de peso é em gramas (inclusive tem muitos produtos abaixo de 1k, por isso foi configurado dessa forma). Quando vou utilizar este plugin, ele acaba passando o peso como se fosse por kg, vindo um valor 1000* maior. Seria possível adaptar uma verificação da unidade de medida como é na maioria dos plugins de frete?

**Comment by phscezario** [comment]
Olá Davi, vou dar uma olhadinha nisso, assim que conseguir ver, te retorno por aqui mesmo. Obrigado.

**Comment by phscezario** [comment]
Pronto, fiz uma atualização, agora vai funcionar com kg (quilos) e g (gramas), obrigado pelo feedback.

**Comment by davioliveiraweb** [comment]
Obrigado pela atenção. Infelizmente não deu certo. No cálculo, tanto pna página do produto, quanto no carrinho, continuou com o mesmo problema. 

Até olhei aqui se eu conseguiria resolver de forma ágil complementando seu código, e enviar um PR. Como meu cliente estava precisando de um solução, fiz um fork e manipulei o peso (dividindo por 1000) na classe WRRS_RTE_Shipping_API. Aí acabei ficando com esse fork fixo para peso em gramas.

**Comment by phscezario** [comment]
Uma pena que não funcionou, e o pior que eu fiz exatamente a mesma coisa, estou mandando um print em anexo, a única coisa que fiz, foi verificar se o peso esta como "g" e dividi por 1000. Porém adicionei essa verificação em outra classe, talvez seja algum problema de cachê, da uma olhadinha caso decida não manter esse fork. Abraço.

![image](https://github.com/phscezario/wc-rte-rodonaves-shipping/assets/42182393/a6c18405-ef92-4ed4-823f-9040f6ceacb4)

**Comment by recaetanodivox** [comment]
@davioliveiraweb acredito que eu esteja passando pelo mesmo problema. Você tem como compartilhar a sua solução???

**Comment by recaetanodivox** [comment]
Porém no meu caso o plugin também não consegue carregar o peso de itens variáveis. Somente de produtos simples...

**Comment by davioliveiraweb** [comment]
> Estou enfrentando um problema com o cálculo do valor. Estou trabalhando em uma loja onde a medida de peso é em gramas (inclusive tem muitos produtos abaixo de 1k, por isso foi configurado dessa forma). Quando vou utilizar este plugin, ele acaba passando o peso como se fosse por kg, vindo um valor 1000* maior. Seria possível adaptar uma verificação da unidade de medida como é na maioria dos plugins de frete?

No meu caso eu fiz o que relatei ali em cima:

"Como meu cliente estava precisando de um solução, fiz um fork e manipulei o peso (dividindo por 1000) na classe WRRS_RTE_Shipping_API. Aí acabei ficando com esse fork fixo para peso em gramas."

Mas já adianto que não deve funcionar para seu problema. Na minha situação ele pegava o peso certinho, porém apresentava problema ao calcular.
